### ISSUE TITLE
Front wiki page, create issues for 1st milestone

### ISSUE THREAD

**Issue by dudko** [jirmauritz/AirportManager#1]
* finish front page - diagrams, descriptions
* create and assign issues as discussed on meeting  (20.10.2015)

**Comment by dudko** [comment]
Issues created just after the meeting. Main wiki page is rather simple, but provides all required points.

**Comment by jirmauritz** [comment]
nice work ;)

**Comment by wallecnik** [comment]
Updated front page - deleted lombok, updated to new entity class diagram
