### ISSUE TITLE
Create interface to facade and service for Steward entity

### ISSUE THREAD

**Issue by jirmauritz** [jirmauritz/AirportManager#10]
plus DTO entities

**Comment by wallecnik** [comment]
Done 311ae7cb03578380e0d59ecf246ff4195995cf49

**Comment by wallecnik** [comment]
Add methods find all available stewards

**Comment by wallecnik** [comment]
Review findBy*() methods - remove or keep

**Comment by wallecnik** [comment]
Make it return Set, not SortedSet

**Comment by wallecnik** [comment]
SortedSet -> Set, fixed implementations.

**Comment by wallecnik** [comment]
return ID from create on service and facade return void from update on service and facade
