### ISSUE TITLE
Create interface to facade and service for Airplane entity

### ISSUE THREAD

**Issue by jirmauritz** [jirmauritz/AirportManager#11]
plus DTO entities

**Comment by wallecnik** [comment]
Add isAvailable() and getAllAvailable()

**Comment by wallecnik** [comment]
Review findBy*() methods - remove or keep

**Comment by wallecnik** [comment]
Make it return Set, not SortedSet

**Comment by dudko** [comment]
Everything should be completed. Check my last two commits fc6c88adee01807624aab3860d6226ef30600c87 c0d39d6538f6a5f46bf4fdf6267b1e9d3127bfc1

**Comment by wallecnik** [comment]
return ID from create on service and facade return void from update on service and facade
