### ISSUE TITLE
Implementation of DestinationService and DestinationFacade

### ISSUE THREAD

**Issue by wallecnik** [jirmauritz/AirportManager#19]

**Comment by wallecnik** [comment]
Review according to interface

**Comment by jirmauritz** [comment]
solved with commit b6fa963310f8d742d692f538afc962d5824cbc61, 45ecac6aecebc819f58541e323c3dcce0129f8eb and 3dcc3bccc91d163ef4e09bfd215183b6f909ae29

**Comment by wallecnik** [comment]
return ID from create on service and update return void from update on service and facade
