### ISSUE TITLE
Create REST API as a Spring MVC controller

### ISSUE THREAD

**Issue by jirmauritz** [jirmauritz/AirportManager#22]
- based on the e-shop project
- any entity, others will be copied

**Comment by wallecnik** [comment]
Include README file with instructions, how to test REST more at [Milestone 3 description](https://is.muni.cz/auth/elearning/warp?fakulta=1433;obdobi=6383;studium=647771;predmet=869910;lang=cs;furl=%2Fauth%2Fel%2F1433%2Fpodzim2015%2FPA165%2Fseminars.qwarp;so=dd;qurl=%2Fel%2F1433%2Fpodzim2015%2FPA165%2Fseminars.qwarp;prejit=3361389)
