### ISSUE TITLE
Entity Flight, DAO Steward, JPA Airplane, Unit test Destination

### ISSUE THREAD

**Issue by dudko** [jirmauritz/AirportManager#4]
* create entity **Flight** 
* create a DAO layer interface (with proper javadoc) for entity **Steward**
* create the JPA implementation of the DAO class (CRUD operations are enough for the first checkpoint) for **Airplane**
* create unit tests for DAO class **Destination**

**Comment by lenkahe** [comment]
Flight + StewardDao implemented.
Do we need DaoImpl if we use Spring data?
Do we use Spring data?

**Comment by jirmauritz** [comment]
It looks like we dont, let's stick to the course structure of project.
Lenka, please add at least CRUD operation and findAll to the StewardDao, thanks.

**Comment by jirmauritz** [comment]
Please, rename AirplainDaoImpl to AirplaneDaoImpl, thanks.

**Comment by wallecnik** [comment]
Created pull request for entity Flight's equals() method for comparing times not by equals on objects, but by equality of milliseconds.

Runtime types returned from database are java.sql.Timestamp and this class violates general contract of equals method (not symmetric). Timestamp saves nanoseconds which does not appear in java.util.Date and therefore Timestamp does not found nanoseconds in Date and claims, that any Date is not equal to it. If called on Date object, equals works fine.

**Comment by lenkahe** [comment]
Sorry for AirplainDaoImpl, it is fixed. But Airplane is not my entity (setCapacity(String type)).
