### ISSUE TITLE
Entity Steward, DAO Airplane, JPA Destination, Unit test Flight

### ISSUE THREAD

**Issue by dudko** [jirmauritz/AirportManager#5]
* create entity **Steward** 
* create a DAO layer interface (with proper javadoc) for entity **Airplane**
* create the JPA implementation of the DAO class (CRUD operations are enough for the first checkpoint) for **Destination**
* create unit tests for DAO class **Flight**

**Comment by dudko** [comment]
Hi,
I've just checked the current state of your implementations. I would say, that **FlightDaoTest** should be **FlightDaoImplTest**. We do not test the interface, but it's implementation. Don't you think so?

**Comment by wallecnik** [comment]
Right - point taken, I'll work on it today and change it.

**Comment by wallecnik** [comment]
Entity Steward created, Airplane DAO interface created, no JavaDoc yet, Destination DAO implementation created. See b1bfaf97bc71444e29c94572cf9e9ae361926011 for more
