### ISSUE TITLE
Create interface to facade and service for Destination entity

### ISSUE THREAD

**Issue by jirmauritz** [jirmauritz/AirportManager#9]
plus DTO entities

**Comment by jirmauritz** [comment]
Alse created simple Service implementation.

**Comment by wallecnik** [comment]
Review findBy*() methods - remove or keep

**Comment by wallecnik** [comment]
Review findBy*() methods - remove or keep

**Comment by jirmauritz** [comment]
keeping all

**Comment by wallecnik** [comment]
return ID from create on service and facade return void from update on service and facade
